---
- name: python_modules | Installing Python Pip
  easy_install:
    name: "pip"
    state: "present"

- name: python_modules | Installing tower-cli
  pip:
    name: "ansible-tower-cli"
    state: "present"
  ignore_errors: true
  when: >
        install_tower_cli is defined and
        install_tower_cli
