---
- name: users | Generating Jenkins SSH Keys
  user:
    name: "jenkins"
    generate_ssh_key: yes

- name: users | Adding Jenkins Account To Sudoers
  lineinfile:
    dest: "/etc/sudoers"
    regexp: "^jenkins ALL"
    line: "jenkins ALL=(ALL) NOPASSWD:ALL"
    validate: "visudo -cf %s"
    state: "present"
  when: >
        enable_jenkins_sudo is defined and
        enable_jenkins_sudo

- name: users | Downloading Jenkins SSH Public Key
  fetch:
    src: "{{ jenkins_home_dir }}/.ssh/id_rsa.pub"
    dest: "./ssh_pub_keys/jenkins@{{ ansible_hostname }}.pub"
    flat: yes

- name: Change ownership Home Directory
  file: 
    path: "{{ jenkins_home_dir }}"
    recurse: yes
    owner: jenkins
    group: jenkins

- name: Update /etc/default/jenkins on Ubuntu
  template: src=../ansible/roles/jenkins/templates/etc/default/jenkins.j2 dest=/etc/default/jenkins
  when: ansible_os_family == "Debian"
